name: Linting

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches:
      - master
    paths:
      - "src/**"
      - "tests/**"

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint src with flake8
        working-directory: src
        run: |
          flake8 . --count --select=E7,E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint tests with flake8
        working-directory: tests
        run: |
          flake8 . --count --select=E7,E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Lint src with black
        working-directory: src
        run: |
          black . --check
      - name: Lint tests with black
        working-directory: tests
        run: |
          black . --check
