name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Install source code as package
      run: |
        cd src/ && pip install -e .

    - name: Test with pytest
      run: |
        cd tests/ && pytest feature_model/organizer_test.py -k get_helical_sep